import { MetadataRoute } from 'next'
import { getSiteBaseUrl } from '@/utils/siteUrl'

export default function sitemap(): MetadataRoute.Sitemap {
  // sitemap에는 절대 URL만 허용되므로 공통 유틸에서 base URL을 확정한다.
  // metadata와 동일한 값으로 맞춰야 검색 엔진이 canonical과 sitemap을 일치시킨다.
  const baseUrl = getSiteBaseUrl()

  // 정적 라우트들을 일괄 정의한다.
  // Next.js App Router의 각 도구 페이지 폴더를 명시적으로 나열해 검색 엔진이 모든 툴을 인덱싱할 수 있도록 한다.
  const routes = [
    '',
    '/about',
    '/faq',
    '/privacy',
    '/terms',
    '/contact',
    '/snippets',
    '/changelog',
    // Encoding
    '/base64',
    '/url',
    '/html-entities',
    '/base64-file',
    '/image-base64',
    '/data-url',
    // Security
    '/jasypt',
    '/jwt-keys',
    '/hash',
    '/password',
    '/jwt-signer',
    '/bcrypt',
    '/hmac',
    '/otp',
    '/basic-auth',
    '/string-obfuscator',
    '/crypto-bundle',
    '/regex-safety',
    '/csp',
    '/sri',
    '/env-crypto',
    '/ssh-keys',
    '/saml',
    '/oauth',
    // Data Format
    '/json',
    '/jsonl',
    '/json-flatten',
    '/graphql',
    '/jwt',
    '/sql',
    '/mybatis',
    '/csv',
    '/html',
    '/yaml-json',
    '/yaml-toml',
    '/json-toml',
    '/xml-json',
    '/markdown-html',
    '/json-minify',
    '/json-csv',
    '/json-diff',
    '/json-path',
    '/json-schema',
    '/schema-to-ts',
    '/openapi',
    '/schema-mock',
    '/env-manager',
    '/env-diff',
    '/code-minifier',
    '/sql-builder',
    '/schema-visualizer',
    // Generators
    '/uuid',
    '/qrcode',
    '/lorem',
    '/token-generator',
    '/token-counter',
    '/ulid',
    '/port-generator',
    '/emoji-picker',
    '/meta-tags',
    '/css-gradient',
    '/box-shadow',
    '/mock-data',
    '/exif',
    // Converters
    '/timestamp',
    '/color',
    '/case',
    '/baseconv',
    '/roman-numeral',
    '/temp-converter',
    '/svg-optimizer',
    '/curl-converter',
    // Text
    '/slugify',
    '/nato-alphabet',
    '/text-binary',
    '/text-unicode',
    '/text-stats',
    '/log-redactor',
    '/numeronym',
    '/list-converter',
    '/email-normalizer',
    '/markdown-table',
    '/sorter',
    // Calculators
    '/math-eval',
    '/percentage-calc',
    '/semver',
    // Info
    '/http-status',
    '/mime-types',
    '/keycode',
    '/device-info',
    '/user-agent',
    '/a11y-check',
    // Linux
    '/chmod',
    '/regex',
    '/cron',
    '/cron-human',
    '/gitignore-generator',
    // Network
    '/ipcalc',
    '/diff',
    '/url-parser',
    '/ipv4-converter',
    '/http-headers',
    '/security-headers',
    '/cookie-parser',
    '/http-builder',
    '/websocket',
    '/ssl-cert',
    '/dns-lookup',
    '/cors',
    '/latency',
    '/api-response-time',
    // Workflow
    '/commit-message',
    '/dependency-checker',
    '/regex-debugger',
    '/patch-viewer',
    // Files
    '/file-hash',
    '/pdf-metadata',
    '/favicon',
    // Frontend
    '/color-palette',
    '/layout-playground',
    '/easing',
    '/breakpoint-tester',
    // Additional tools
    '/phone-parser',
    '/iban-validator',
    '/ascii-art',
    '/mac-address',
    '/password-strength',
    '/bip39',
  ]

  // 각 경로를 Next.js가 요구하는 Sitemap 형태로 변환한다.
  // lastModified는 호출 시점의 시간으로 지정하여 최신 업데이트 신호를 검색엔진에 전달한다.
  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1 : 0.8,
  }))
}
