'use client'

import { useState, useEffect } from 'react'
import ToolCard from './ToolCard'
import TextAreaWithCopy from './TextAreaWithCopy'
import { useLanguage } from '@/contexts/LanguageContext'

type HookType = 'pre-commit' | 'commit-msg' | 'pre-push' | 'post-merge' | 'post-checkout'

interface HookConfig {
  hookType: HookType
  lintOnCommit: boolean
  formatOnCommit: boolean
  runTests: boolean
  preventLargeFiles: boolean
  maxFileSize: string
  enforceConventionalCommits: boolean
  preventSecrets: boolean
  branchProtection: boolean
  protectedBranches: string
  customScript: string
}

const defaultConfig: HookConfig = {
  hookType: 'pre-commit',
  lintOnCommit: true,
  formatOnCommit: true,
  runTests: false,
  preventLargeFiles: true,
  maxFileSize: '5',
  enforceConventionalCommits: false,
  preventSecrets: true,
  branchProtection: false,
  protectedBranches: 'main,master',
  customScript: '',
}

const hookDescriptions: Record<HookType, string> = {
  'pre-commit': 'Runs before a commit is created',
  'commit-msg': 'Runs after commit message is entered',
  'pre-push': 'Runs before push to remote',
  'post-merge': 'Runs after a merge operation',
  'post-checkout': 'Runs after checkout/switch',
}

function generateHookScript(config: HookConfig): string {
  const lines: string[] = ['#!/bin/bash', '', '# Git Hook generated by Dev Tools', '']

  // Colors for output
  lines.push('RED="\\033[0;31m"')
  lines.push('GREEN="\\033[0;32m"')
  lines.push('YELLOW="\\033[0;33m"')
  lines.push('NC="\\033[0m" # No Color')
  lines.push('')

  switch (config.hookType) {
    case 'pre-commit':
      if (config.preventSecrets) {
        lines.push('# Check for potential secrets')
        lines.push('echo "Checking for potential secrets..."')
        lines.push('SECRET_PATTERNS="password|secret|api_key|apikey|access_token|private_key"')
        lines.push('if git diff --cached --name-only | xargs grep -l -E "$SECRET_PATTERNS" 2>/dev/null; then')
        lines.push('    echo -e "${RED}ERROR: Potential secrets detected in staged files${NC}"')
        lines.push('    echo "Please review the files above and remove sensitive data"')
        lines.push('    exit 1')
        lines.push('fi')
        lines.push('')
      }

      if (config.preventLargeFiles) {
        lines.push(`# Check for large files (>${config.maxFileSize}MB)`)
        lines.push(`MAX_SIZE=$((${config.maxFileSize} * 1024 * 1024))`)
        lines.push('for file in $(git diff --cached --name-only); do')
        lines.push('    if [ -f "$file" ]; then')
        lines.push('        size=$(wc -c < "$file")')
        lines.push('        if [ "$size" -gt "$MAX_SIZE" ]; then')
        lines.push('            echo -e "${RED}ERROR: $file is larger than ' + config.maxFileSize + 'MB${NC}"')
        lines.push('            exit 1')
        lines.push('        fi')
        lines.push('    fi')
        lines.push('done')
        lines.push('')
      }

      if (config.lintOnCommit) {
        lines.push('# Run linter')
        lines.push('echo "Running linter..."')
        lines.push('if command -v npm &> /dev/null && [ -f "package.json" ]; then')
        lines.push('    npm run lint --if-present || {')
        lines.push('        echo -e "${RED}Linting failed. Please fix errors before committing.${NC}"')
        lines.push('        exit 1')
        lines.push('    }')
        lines.push('fi')
        lines.push('')
      }

      if (config.formatOnCommit) {
        lines.push('# Run formatter')
        lines.push('echo "Checking code formatting..."')
        lines.push('if command -v npm &> /dev/null && [ -f "package.json" ]; then')
        lines.push('    npm run format:check --if-present || {')
        lines.push('        echo -e "${YELLOW}Code formatting issues detected. Running formatter...${NC}"')
        lines.push('        npm run format --if-present')
        lines.push('        git add -u')
        lines.push('    }')
        lines.push('fi')
        lines.push('')
      }

      if (config.runTests) {
        lines.push('# Run tests')
        lines.push('echo "Running tests..."')
        lines.push('if command -v npm &> /dev/null && [ -f "package.json" ]; then')
        lines.push('    npm test --if-present || {')
        lines.push('        echo -e "${RED}Tests failed. Please fix before committing.${NC}"')
        lines.push('        exit 1')
        lines.push('    }')
        lines.push('fi')
        lines.push('')
      }
      break

    case 'commit-msg':
      if (config.enforceConventionalCommits) {
        lines.push('# Enforce Conventional Commits')
        lines.push('COMMIT_MSG_FILE=$1')
        lines.push('COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")')
        lines.push('')
        lines.push('# Pattern for conventional commits')
        lines.push('PATTERN="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-z]+\\))?: .{1,72}"')
        lines.push('')
        lines.push('if ! echo "$COMMIT_MSG" | grep -qE "$PATTERN"; then')
        lines.push('    echo -e "${RED}ERROR: Commit message does not follow Conventional Commits format${NC}"')
        lines.push('    echo ""')
        lines.push('    echo "Format: <type>(<scope>): <description>"')
        lines.push('    echo ""')
        lines.push('    echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"')
        lines.push('    echo ""')
        lines.push('    echo "Example: feat(auth): add login functionality"')
        lines.push('    exit 1')
        lines.push('fi')
        lines.push('')
      }
      break

    case 'pre-push':
      if (config.branchProtection) {
        const branches = config.protectedBranches.split(',').map(b => b.trim())
        lines.push('# Prevent direct push to protected branches')
        lines.push('BRANCH=$(git rev-parse --abbrev-ref HEAD)')
        lines.push(`PROTECTED_BRANCHES="${branches.join(' ')}"`)
        lines.push('')
        lines.push('for protected in $PROTECTED_BRANCHES; do')
        lines.push('    if [ "$BRANCH" = "$protected" ]; then')
        lines.push('        echo -e "${RED}ERROR: Direct push to $protected is not allowed${NC}"')
        lines.push('        echo "Please create a pull request instead"')
        lines.push('        exit 1')
        lines.push('    fi')
        lines.push('done')
        lines.push('')
      }

      if (config.runTests) {
        lines.push('# Run tests before push')
        lines.push('echo "Running tests before push..."')
        lines.push('if command -v npm &> /dev/null && [ -f "package.json" ]; then')
        lines.push('    npm test --if-present || {')
        lines.push('        echo -e "${RED}Tests failed. Push aborted.${NC}"')
        lines.push('        exit 1')
        lines.push('    }')
        lines.push('fi')
        lines.push('')
      }
      break

    case 'post-merge':
      lines.push('# Check if package.json changed')
      lines.push('CHANGED_FILES=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)')
      lines.push('')
      lines.push('if echo "$CHANGED_FILES" | grep -q "package.json"; then')
      lines.push('    echo -e "${YELLOW}package.json changed. Running npm install...${NC}"')
      lines.push('    npm install')
      lines.push('fi')
      lines.push('')
      lines.push('if echo "$CHANGED_FILES" | grep -q "requirements.txt"; then')
      lines.push('    echo -e "${YELLOW}requirements.txt changed. Running pip install...${NC}"')
      lines.push('    pip install -r requirements.txt')
      lines.push('fi')
      lines.push('')
      break

    case 'post-checkout':
      lines.push('# $1 = previous HEAD, $2 = new HEAD, $3 = branch checkout flag (1 if branch)')
      lines.push('PREV_HEAD=$1')
      lines.push('NEW_HEAD=$2')
      lines.push('IS_BRANCH=$3')
      lines.push('')
      lines.push('if [ "$IS_BRANCH" = "1" ]; then')
      lines.push('    # Check if package.json differs between branches')
      lines.push('    if ! git diff --quiet "$PREV_HEAD" "$NEW_HEAD" -- package.json 2>/dev/null; then')
      lines.push('        echo -e "${YELLOW}package.json differs. Running npm install...${NC}"')
      lines.push('        npm install')
      lines.push('    fi')
      lines.push('fi')
      lines.push('')
      break
  }

  if (config.customScript.trim()) {
    lines.push('# Custom script')
    config.customScript.split('\n').forEach(line => {
      lines.push(line)
    })
    lines.push('')
  }

  lines.push('echo -e "${GREEN}Hook passed successfully!${NC}"')
  lines.push('exit 0')

  return lines.join('\n')
}

export default function GitHooksTool() {
  const { t } = useLanguage()
  const [config, setConfig] = useState<HookConfig>(defaultConfig)
  const [output, setOutput] = useState('')

  useEffect(() => {
    setOutput(generateHookScript(config))
  }, [config])

  const updateConfig = (key: keyof HookConfig, value: string | boolean) => {
    setConfig(prev => ({ ...prev, [key]: value }))
  }

  const handleDownload = () => {
    const blob = new Blob([output], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = config.hookType
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <ToolCard
      title={t('githooks.title')}
      description={t('githooks.description')}
    >
      <div className="space-y-6">
        {/* Hook Type Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('githooks.hookType')}
          </label>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-2">
            {(Object.keys(hookDescriptions) as HookType[]).map(type => (
              <button
                key={type}
                onClick={() => updateConfig('hookType', type)}
                className={`px-3 py-2 text-sm rounded transition-colors ${
                  config.hookType === type
                    ? 'bg-blue-500 text-white'
                    : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                }`}
              >
                {type}
              </button>
            ))}
          </div>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
            {hookDescriptions[config.hookType]}
          </p>
        </div>

        {/* Configuration Options */}
        <div className="grid md:grid-cols-2 gap-4">
          {config.hookType === 'pre-commit' && (
            <>
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.lintOnCommit}
                  onChange={(e) => updateConfig('lintOnCommit', e.target.checked)}
                  className="rounded border-gray-300"
                />
                <span className="text-gray-700 dark:text-gray-300">{t('githooks.lintOnCommit')}</span>
              </label>

              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.formatOnCommit}
                  onChange={(e) => updateConfig('formatOnCommit', e.target.checked)}
                  className="rounded border-gray-300"
                />
                <span className="text-gray-700 dark:text-gray-300">{t('githooks.formatOnCommit')}</span>
              </label>

              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.runTests}
                  onChange={(e) => updateConfig('runTests', e.target.checked)}
                  className="rounded border-gray-300"
                />
                <span className="text-gray-700 dark:text-gray-300">{t('githooks.runTests')}</span>
              </label>

              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.preventSecrets}
                  onChange={(e) => updateConfig('preventSecrets', e.target.checked)}
                  className="rounded border-gray-300"
                />
                <span className="text-gray-700 dark:text-gray-300">{t('githooks.preventSecrets')}</span>
              </label>

              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.preventLargeFiles}
                  onChange={(e) => updateConfig('preventLargeFiles', e.target.checked)}
                  className="rounded border-gray-300"
                />
                <span className="text-gray-700 dark:text-gray-300">{t('githooks.preventLargeFiles')}</span>
                {config.preventLargeFiles && (
                  <input
                    type="number"
                    value={config.maxFileSize}
                    onChange={(e) => updateConfig('maxFileSize', e.target.value)}
                    className="w-16 px-2 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
                  />
                )}
                <span className="text-sm text-gray-500">MB</span>
              </div>
            </>
          )}

          {config.hookType === 'commit-msg' && (
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={config.enforceConventionalCommits}
                onChange={(e) => updateConfig('enforceConventionalCommits', e.target.checked)}
                className="rounded border-gray-300"
              />
              <span className="text-gray-700 dark:text-gray-300">{t('githooks.conventionalCommits')}</span>
            </label>
          )}

          {config.hookType === 'pre-push' && (
            <>
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.runTests}
                  onChange={(e) => updateConfig('runTests', e.target.checked)}
                  className="rounded border-gray-300"
                />
                <span className="text-gray-700 dark:text-gray-300">{t('githooks.runTests')}</span>
              </label>

              <div className="md:col-span-2">
                <label className="flex items-center gap-2 mb-2">
                  <input
                    type="checkbox"
                    checked={config.branchProtection}
                    onChange={(e) => updateConfig('branchProtection', e.target.checked)}
                    className="rounded border-gray-300"
                  />
                  <span className="text-gray-700 dark:text-gray-300">{t('githooks.branchProtection')}</span>
                </label>
                {config.branchProtection && (
                  <input
                    type="text"
                    value={config.protectedBranches}
                    onChange={(e) => updateConfig('protectedBranches', e.target.value)}
                    placeholder="main, master, develop"
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
                  />
                )}
              </div>
            </>
          )}
        </div>

        {/* Custom Script */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('githooks.customScript')}
          </label>
          <textarea
            value={config.customScript}
            onChange={(e) => updateConfig('customScript', e.target.value)}
            placeholder={t('githooks.customScript.placeholder')}
            rows={4}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white font-mono text-sm"
          />
        </div>

        {/* Output */}
        <div>
          <div className="flex justify-between items-center mb-2">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t('githooks.output.label')}
            </label>
            <button
              onClick={handleDownload}
              className="px-3 py-1 bg-indigo-500 text-white text-sm rounded hover:bg-indigo-600 transition-colors"
            >
              {t('githooks.actions.download')}
            </button>
          </div>
          <TextAreaWithCopy
            value={output}
            readOnly
            rows={20}
          />
        </div>

        {/* Installation Instructions */}
        <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
          <h4 className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">
            {t('githooks.install.title')}
          </h4>
          <ol className="text-sm text-yellow-700 dark:text-yellow-300 space-y-1 list-decimal list-inside">
            <li>{t('githooks.install.step1')}</li>
            <li>{t('githooks.install.step2')}</li>
            <li>{t('githooks.install.step3')}</li>
          </ol>
        </div>
      </div>
    </ToolCard>
  )
}
